### ISSUE TITLE
don't consider examples when analyzing libraries

### ISSUE THREAD

**Issue by sigmaSd** [cackle-rs/cackle#11]
Seems like cackle is considering examples when analyzing libraries, I think it makes sense to ignore them.

**Comment by sigmaSd** [comment]
Same with benches, also in case of benches I sometimes use rust nightly bench feature, so this makes cargo acl fails to build `error[E0554]: `#![feature]` may not be used on the stable release channel`

**Comment by davidlattimore** [comment]
By default, cackle passes `--all-targets`. You can override this in your `cackle.toml` with:

```toml
[common]
build_flags = []
```

**Comment by sigmaSd** [comment]
thanks
