### ISSUE TITLE
Running on an individual workspace member

### ISSUE THREAD

**Issue by jayvdb** [cackle-rs/cackle#22]
One possible workaround for https://github.com/cackle-rs/cackle/issues/20 would be to run `cargo acl` on individual members, with only its dependencies being processed.  It looks like that doesnt work.  Rough idea here is to work out which members are successful, which OOM, and then figure out what is common between the ones which are being killed.

Beyond that problem, it would be useful for us as we have dynamic github actions that create a job for each modified workspace member, only doing the build steps for that workspace member.

Any chance this is feasible?

**Comment by davidlattimore** [comment]
I added `--package` which gets passed through to `cargo`
