### ISSUE TITLE
Display code snippets with syntax highlighting

### ISSUE THREAD

**Issue by repi** [cackle-rs/cackle#4]
Would be nice to show the code diffs in the "Usage details" window with colored syntax highlighting  to more easily be able to read it, esp. as one may be scanning through quite a lot of diffs when triaging with this tool. Though not a high priority as would just be a "nice to have".

Believe seen some Rust syntax highlighting crate that may be easy to integrate

**Comment by davidlattimore** [comment]
Yes, syntax highlighting would be nice - provided whatever provides it isn't too heavy-weight. So something just based on tokens, not full rust-analyzer :) I'm assuming you mean the code snippets BTW - Cackle doesn't display any code diffs currently. It does display diffs of cackle.toml when previewing an automatic edit of the configuration file.

**Comment by repi** [comment]
sorry yes mean the snippets, like this:

![image](https://github.com/davidlattimore/cackle/assets/1262692/417335c8-15bc-4d65-94a5-82fd4fb68784)

**Comment by davidlattimore** [comment]
Thinking about syntax highlighting some more, I'm unsure that a syntax-highlighting library would provide much beyond what a lexer already provides. Cackle already depends on `rustc-ap-rustc_lexer`, so we could take the output of that then assign different colours to different categories of tokens.

**Comment by davidlattimore** [comment]
I just added some basic syntax colouring. I didn't put too much thought into the colours, so if you have opinions on the colours, feel free to tweak and send a PR.
