### ISSUE TITLE
cargo cackle [..]

### ISSUE THREAD

**Issue by pinkforest** [cackle-rs/cackle#9]
Would it make sense to add cargo sub-command so it can be integrated with cargo ?

This is how we do it with e.g. cargo-geiger, audit, deny, hack etc.

**Comment by davidlattimore** [comment]
Possibly, although it could get confusing when using the 'cargo' subcommand. e.g. `cargo cackle cargo test` looks a bit weird compared to just `cackle cargo test`.

What advantage would it give?

**Comment by pinkforest** [comment]
You would use cargo cackle test not duplicate cargo in between

It's idiomatic way to use it and when you publish cargo-cackle it will flow in as cargo cackle

**Comment by davidlattimore** [comment]
I've renamed the crate to `cargo-acl`

**Comment by pinkforest** [comment]
i like cackle more :P

**Comment by pinkforest** [comment]
plus can have both, cackle as backend and cargo-acl just frontend to cackle as lib

**Comment by davidlattimore** [comment]
That's true. I haven't seen a need to have cackle as a lib thus far, but if I do, I'd definitely do it under the name "cackle".

**Comment by pinkforest** [comment]
In [binfire](https://github.com/rinse-repeat/binfire/blob/main/binfire-bin/src/args.rs) I just implement "Runner" traits of library and it gives me flexibility how I run it - it's easier to de-couple from start as binaries and libraries need diff deps

Also exposing de-coupled things as library makes it more easier to test as binaries are harder to test vs a library.
